version: v{build}
max_jobs: 1
configuration: Release
platform: x86
clone_depth: 50
image: Visual Studio 2017
before_build:
- cmd: bootstrap.bat
build:
  project: Hearthstone Collection Tracker.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(appveyor_build_version)'
artifacts:
- path: Hearthstone Collection Tracker\bin\x86\Release\HearthstoneCollectionTracker.dll
  name: Release-dll
- path: Hearthstone Collection Tracker\bin\x86\Debug\HearthstoneCollectionTracker.dll
  name: Debug-dll
- path: Hearthstone Collection Tracker\bin\x86\Debug\HearthstoneCollectionTracker.pdb
  name: Debug-pdb
